google.maps.__gjsload__('geometry', function(_){var Hr=function(a,b){return Math.abs(_.Nc(b-a,-180,180))},Ir=function(a,b,c,d,e){if(!d){c=Hr(a.lng(),c)/Hr(a.lng(),b.lng());if(!e)return e=Math.sin(_.ec(a.lat())),e=Math.log((1+e)/(1-e))/2,b=Math.sin(_.ec(b.lat())),_.fc(2*Math.atan(Math.exp(e+c*(Math.log((1+b)/(1-b))/2-e)))-Math.PI/2);a=e.fromLatLngToPoint(a);b=e.fromLatLngToPoint(b);return e.fromPointToLatLng(new _.M(a.x+c*(b.x-a.x),a.y+c*(b.y-a.y))).lat()}e=_.ec(a.lat());a=_.ec(a.lng());d=_.ec(b.lat());b=_.ec(b.lng());c=_.ec(c);return _.Nc(_.fc(Math.atan2(Math.sin(e)*
Math.cos(d)*Math.sin(c-b)-Math.sin(d)*Math.cos(e)*Math.sin(c-a),Math.cos(e)*Math.cos(d)*Math.sin(a-b))),-90,90)},Jr=_.n(),Kr={containsLocation:function(a,b){var c=_.Nc(a.lng(),-180,180),d=!!b.get("geodesic"),e=b.get("latLngs"),f=b.get("map");f=!d&&f?f.getProjection():null;for(var g=!1,h=0,k=e.getLength();h<k;++h)for(var l=e.getAt(h),m=0,q=l.getLength();m<q;++m){var r=l.getAt(m),v=l.getAt((m+1)%q),u=_.Nc(r.lng(),-180,180),w=_.Nc(v.lng(),-180,180),x=Math.max(u,w);u=Math.min(u,w);(180<x-u?c>=x||c<u:
c<x&&c>=u)&&Ir(r,v,c,d,f)<a.lat()&&(g=!g)}return g||Kr.isLocationOnEdge(a,b)}};_.bb("PolyGeometry.containsLocation",Kr.containsLocation);
Kr.isLocationOnEdge=function(a,b,c){c=c||1E-9;var d=_.Nc(a.lng(),-180,180),e=b instanceof _.qh,f=!!b.get("geodesic"),g=b.get("latLngs");b=b.get("map");b=!f&&b?b.getProjection():null;for(var h=0,k=g.getLength();h<k;++h)for(var l=g.getAt(h),m=l.getLength(),q=e?m:m-1,r=0;r<q;++r){var v=l.getAt(r),u=l.getAt((r+1)%m),w=_.Nc(v.lng(),-180,180),x=_.Nc(u.lng(),-180,180),A=Math.max(w,x),D=Math.min(w,x);if(w=1E-9>=Math.abs(_.Nc(w-x,-180,180))&&(Math.abs(_.Nc(w-d,-180,180))<=c||Math.abs(_.Nc(x-d,-180,180))<=
c)){w=a.lat();x=Math.min(v.lat(),u.lat())-c;var E=Math.max(v.lat(),u.lat())+c;w=w>=x&&w<=E}if(w)return!0;if(180<A-D?d+c>=A||d-c<=D:d+c>=D&&d-c<=A)if(v=Ir(v,u,d,f,b),Math.abs(v-a.lat())<c)return!0}return!1};_.bb("PolyGeometry.isLocationOnEdge",Kr.isLocationOnEdge);var Lr={computeHeading:function(a,b){var c=_.vd(a),d=_.wd(a);a=_.vd(b);b=_.wd(b)-d;return _.Nc(_.fc(Math.atan2(Math.sin(b)*Math.cos(a),Math.cos(c)*Math.sin(a)-Math.sin(c)*Math.cos(a)*Math.cos(b))),-180,180)}};_.bb("Spherical.computeHeading",Lr.computeHeading);
Lr.computeOffset=function(a,b,c,d){b/=d||6378137;c=_.ec(c);var e=_.vd(a);a=_.wd(a);d=Math.cos(b);b=Math.sin(b);var f=Math.sin(e);e=Math.cos(e);var g=d*f+b*e*Math.cos(c);return new _.P(_.fc(Math.asin(g)),_.fc(a+Math.atan2(b*e*Math.sin(c),d-f*g)))};_.bb("Spherical.computeOffset",Lr.computeOffset);
Lr.computeOffsetOrigin=function(a,b,c,d){c=_.ec(c);b/=d||6378137;d=Math.cos(b);var e=Math.sin(b)*Math.cos(c);b=Math.sin(b)*Math.sin(c);c=Math.sin(_.vd(a));var f=e*e*d*d+d*d*d*d-d*d*c*c;if(0>f)return null;var g=e*c+Math.sqrt(f);g/=d*d+e*e;var h=(c-e*g)/d;g=Math.atan2(h,g);if(g<-Math.PI/2||g>Math.PI/2)g=e*c-Math.sqrt(f),g=Math.atan2(h,g/(d*d+e*e));if(g<-Math.PI/2||g>Math.PI/2)return null;a=_.wd(a)-Math.atan2(b,d*Math.cos(g)-e*Math.sin(g));return new _.P(_.fc(g),_.fc(a))};
_.bb("Spherical.computeOffsetOrigin",Lr.computeOffsetOrigin);Lr.interpolate=function(a,b,c){var d=_.vd(a),e=_.wd(a),f=_.vd(b),g=_.wd(b),h=Math.cos(d),k=Math.cos(f);b=Lr.lf(a,b);var l=Math.sin(b);if(1E-6>l)return new _.P(a.lat(),a.lng());a=Math.sin((1-c)*b)/l;c=Math.sin(c*b)/l;b=a*h*Math.cos(e)+c*k*Math.cos(g);e=a*h*Math.sin(e)+c*k*Math.sin(g);return new _.P(_.fc(Math.atan2(a*Math.sin(d)+c*Math.sin(f),Math.sqrt(b*b+e*e))),_.fc(Math.atan2(e,b)))};_.bb("Spherical.interpolate",Lr.interpolate);
Lr.lf=function(a,b){var c=_.vd(a);a=_.wd(a);var d=_.vd(b);b=_.wd(b);return 2*Math.asin(Math.sqrt(Math.pow(Math.sin((c-d)/2),2)+Math.cos(c)*Math.cos(d)*Math.pow(Math.sin((a-b)/2),2)))};Lr.computeDistanceBetween=function(a,b,c){c=c||6378137;return Lr.lf(a,b)*c};_.bb("Spherical.computeDistanceBetween",Lr.computeDistanceBetween);Lr.computeLength=function(a,b){b=b||6378137;var c=0;a instanceof _.ge&&(a=a.getArray());for(var d=0,e=a.length-1;d<e;++d)c+=Lr.computeDistanceBetween(a[d],a[d+1],b);return c};
_.bb("Spherical.computeLength",Lr.computeLength);Lr.computeArea=function(a,b){return Math.abs(Lr.computeSignedArea(a,b))};_.bb("Spherical.computeArea",Lr.computeArea);Lr.computeSignedArea=function(a,b){b=b||6378137;a instanceof _.ge&&(a=a.getArray());for(var c=a[0],d=0,e=1,f=a.length-1;e<f;++e)d+=Lr.Oj(c,a[e],a[e+1]);return d*b*b};_.bb("Spherical.computeSignedArea",Lr.computeSignedArea);Lr.Oj=function(a,b,c){return Lr.Pj(a,b,c)*Lr.Nk(a,b,c)};
Lr.Pj=function(a,b,c){var d=[a,b,c,a];a=[];for(c=b=0;3>c;++c)a[c]=Lr.lf(d[c],d[c+1]),b+=a[c];b/=2;d=Math.tan(b/2);for(c=0;3>c;++c)d*=Math.tan((b-a[c])/2);return 4*Math.atan(Math.sqrt(Math.abs(d)))};
Lr.Nk=function(a,b,c){a=[a,b,c];b=[];for(c=0;3>c;++c){var d=a[c],e=_.vd(d);d=_.wd(d);var f=b[c]=[];f[0]=Math.cos(e)*Math.cos(d);f[1]=Math.cos(e)*Math.sin(d);f[2]=Math.sin(e)}return 0<b[0][0]*b[1][1]*b[2][2]+b[1][0]*b[2][1]*b[0][2]+b[2][0]*b[0][1]*b[1][2]-b[0][0]*b[2][1]*b[1][2]-b[1][0]*b[0][1]*b[2][2]-b[2][0]*b[1][1]*b[0][2]?1:-1};var Mr={decodePath:function(a){for(var b=_.J(a),c=Array(Math.floor(a.length/2)),d=0,e=0,f=0,g=0;d<b;++g){var h=1,k=0;do{var l=a.charCodeAt(d++)-63-1;h+=l<<k;k+=5}while(31<=l);e+=h&1?~(h>>1):h>>1;h=1;k=0;do l=a.charCodeAt(d++)-63-1,h+=l<<k,k+=5;while(31<=l);f+=h&1?~(h>>1):h>>1;c[g]=new _.P(1E-5*e,1E-5*f,!0)}c.length=g;return c}};_.bb("PolylineCodec.decodePath",Mr.decodePath);
Mr.encodePath=function(a){a instanceof _.ge&&(a=a.getArray());return Mr.bm(a,function(b){return[Math.round(1E5*b.lat()),Math.round(1E5*b.lng())]})};_.bb("PolylineCodec.encodePath",Mr.encodePath);Mr.bm=function(a,b){for(var c=[],d=[0,0],e,f=0,g=_.J(a);f<g;++f)e=b?b(a[f]):a[f],Mr.Vh(e[0]-d[0],c),Mr.Vh(e[1]-d[1],c),d=e;return c.join("")};Mr.Vh=function(a,b){Mr.cm(0>a?~(a<<1):a<<1,b)};Mr.cm=function(a,b){for(;32<=a;)b.push(String.fromCharCode((32|a&31)+63)),a>>=5;b.push(String.fromCharCode(a+63))};_.y.google.maps.geometry={encoding:Mr,spherical:Lr,poly:Kr};_.p=Jr.prototype;_.p.decodePath=Mr.decodePath;_.p.encodePath=Mr.encodePath;_.p.computeDistanceBetween=Lr.computeDistanceBetween;_.p.interpolate=Lr.interpolate;_.p.computeHeading=Lr.computeHeading;_.p.computeOffset=Lr.computeOffset;_.p.computeOffsetOrigin=Lr.computeOffsetOrigin;_.Ze("geometry",new Jr);});
